/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan10;
import static pertemuan10.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nirmala Sanratu
 * TGL 24 Mei 2025
 */
public class fMahasiswa extends javax.swing.JFrame {
     DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form fMahasiswa
     * @throws java.sql.SQLException
     */
    public fMahasiswa() throws SQLException {
        initComponents();
        tmhs.setModel(dtm);
        dtm.addColumn("Nama Mahasiswa");
        dtm.addColumn("NIM");
        dtm.addColumn("Jenis Kelamin");
        dtm.addColumn("Prodi");
        
        lsDtMhs();
        fieldEnabled(false);
        tombol(false);
        cBaru.setEnabled(true);
        cTutup.setEnabled(true);
                
    }
    private void fieldEnabled(boolean opsi){
        txNIM.setEditable(opsi);
        txNAMA.setEditable(opsi);
        txJK.setEditable(opsi);
        txPRODI.setEditable(opsi);
            
        }
        
        private void tombol(boolean opsi){
            cBaru.setEnabled(opsi);
            cUbah.setEnabled(opsi);
            cHapus.setEnabled(opsi);
            cTutup.setEnabled(opsi);
   
        }
        private void clearForm(){
            txNIM.setText("");
            txNAMA.setText("");
            txPRODI.setText("");
            txJK.setText("");
            
        }
    
    
    private void lsDtMhs() throws SQLException{
    Connection cnn = koneksi ();
    
    dtm.getDataVector().removeAllElements();
    dtm.fireTableDataChanged();
    
    
    if( !cnn.isClosed() ){
         PreparedStatement ps = cnn. prepareStatement("SELECT * FROM mhs;");
         ResultSet rs = ps.executeQuery();
         while( rs.next() ){
             Object [] dta = new Object [4];
             dta[0] = rs.getString("NAMA");
             dta[1] = rs.getString("NIM");
             dta[2] = rs.getString("PRODI");
             dta[3] = rs.getString("JKEL");
             
             
           dtm.addRow(dta);
             
         }
         cnn.close();
        
    }
    }
private void storeData() throws SQLException{
        Connection cnn = koneksi();
        if(!cnn.isClosed()){
            PreparedStatement ps = cnn.prepareStatement("INSERT INTO mhs(NIM,NAMA,PRODI,JKEL) VALUES(?,?,?,?);");
            ps.setString(1, txNIM.getText());
            ps.setString(2, txNAMA.getText());
            ps.setString(3, txPRODI.getText());
            ps.setString(4, txJK.getText());
            ps.executeUpdate();
            cnn.close();
        }
    }
    private void updateData()throws SQLException{ 
        Connection cnn = koneksi();
        if(!cnn.isClosed()){
            PreparedStatement ps = cnn.prepareStatement("UPDATE mhs SET NAMA=?,PRODI=?,JKEL=? WHERE NIM=?;");
            ps.setString(1, txNAMA.getText());
            ps.setString(2, txPRODI.getText());
            ps.setString(3, txJK.getText());
            ps.setString(4, txNIM.getText());
            ps.executeUpdate();
            cnn.close();
        }
        
    }
    private void destoryData()throws SQLException{
        Connection cnn = koneksi();
        if(!cnn.isClosed()){
            PreparedStatement ps = cnn.prepareStatement("DELETE FROM mhs WHERE NIM=?;");
            ps.setString(4, txNIM.getText());
            ps.executeUpdate();
            cnn.close();
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txNIM = new javax.swing.JTextField();
        txNAMA = new javax.swing.JTextField();
        txJK = new javax.swing.JTextField();
        txPRODI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tmhs = new javax.swing.JTable();
        cBaru = new javax.swing.JButton();
        cUbah = new javax.swing.JButton();
        cHapus = new javax.swing.JButton();
        cTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 18)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setText("Data Mahasiswa");

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel2.setText("NIM");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel3.setText("Nama Mahasiswa");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setText("Program Studi");

        txNIM.setBackground(new java.awt.Color(255, 204, 153));
        txNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNIMActionPerformed(evt);
            }
        });

        txNAMA.setBackground(new java.awt.Color(255, 204, 153));
        txNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNAMAActionPerformed(evt);
            }
        });

        txJK.setBackground(new java.awt.Color(255, 204, 153));
        txJK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txJKActionPerformed(evt);
            }
        });

        txPRODI.setBackground(new java.awt.Color(255, 204, 153));
        txPRODI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPRODIActionPerformed(evt);
            }
        });

        tmhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tmhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tmhs);

        cBaru.setBackground(new java.awt.Color(51, 204, 255));
        cBaru.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        cBaru.setText("Baru");
        cBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBaruActionPerformed(evt);
            }
        });

        cUbah.setBackground(new java.awt.Color(255, 51, 255));
        cUbah.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        cUbah.setText("Ubah");
        cUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUbahActionPerformed(evt);
            }
        });

        cHapus.setBackground(new java.awt.Color(255, 204, 204));
        cHapus.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        cHapus.setText("Hapus");

        cTutup.setBackground(new java.awt.Color(51, 255, 51));
        cTutup.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        cTutup.setText("Tutup");
        cTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txJK, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txPRODI, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cBaru)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cUbah)
                                .addGap(9, 9, 9)
                                .addComponent(cHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cTutup)))
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2)
                        .addComponent(txNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(17, 17, 17)
                        .addComponent(txJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txPRODI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNIMActionPerformed

    private void txNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNAMAActionPerformed

    private void txJKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txJKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txJKActionPerformed

    private void txPRODIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPRODIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPRODIActionPerformed

    private void cUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cUbahActionPerformed

    private void cTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTutupActionPerformed
      int opsi =JOptionPane.showOptionDialog(this,
             "yakin akn menutup form?",
             "konfirmasi tutup form?",
             JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,null,null,null);
        
      if (opsi == JOptionPane.YES_OPTION){  
        System.exit(0);
     }
    }//GEN-LAST:event_cTutupActionPerformed

    private void tmhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmhsMouseClicked
        txNIM.setText(tmhs.getValueAt(tmhs.getSelectedRow(),  1 ).toString());
        txNAMA.setText(tmhs.getValueAt(tmhs.getSelectedRow() , 0 ).toString());
       String jkx = (tmhs.getValueAt(tmhs.getSelectedRow() , 2 ).toString().equals("L"))?"Laki-Laki":"Perempuan";
        txJK.setText(jkx);
        txPRODI.setText(tmhs.getValueAt(tmhs.getSelectedRow() , 3 ).toString());
        cUbah.setEnabled(true);
        cHapus.setEnabled(true);
    }//GEN-LAST:event_tmhsMouseClicked

    private void cBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBaruActionPerformed
      if(cBaru.getText().equals("Baru")){
         cBaru.setText("simpan");
         cTutup.setText("Batal");
         cUbah.setEnabled(false);
         cHapus.setEnabled(false);
         clearForm();
         fieldEnabled(true);
      }else{
          if(!txNIM.getText().equals("")){
              try{
                  storeData();
                  lsDtMhs();
              } catch (SQLException ex) {
                  Logger.getLogger(fMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
             
              }
          }
         cBaru.setText("Baru");
         cTutup.setText("Tutup");
         clearForm();
         fieldEnabled(false);
      }
    }//GEN-LAST:event_cBaruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new fMahasiswa().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(fMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cBaru;
    private javax.swing.JButton cHapus;
    private javax.swing.JButton cTutup;
    private javax.swing.JButton cUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tmhs;
    private javax.swing.JTextField txJK;
    private javax.swing.JTextField txNAMA;
    private javax.swing.JTextField txNIM;
    private javax.swing.JTextField txPRODI;
    // End of variables declaration//GEN-END:variables
}
